version: "3.8"

services:
  db:  # Main app database
    image: postgres:16
    networks:
      - cp-net
    container_name: cp-db
    environment:
      POSTGRES_DB: careerpath
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "5432:5432"
    volumes:
      - cp_pg:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - cp-net
    container_name: cp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    build:
      context: ../backend
    networks:
      - cp-net
    container_name: cp-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    networks:
      - cp-net
    container_name: cp-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  sonarqube-db:
    image: postgres:16
    networks:
      - cp-net
    container_name: cp-sonar-db
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonar_db:/var/lib/postgresql/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:10.4.1-community
    container_name: cp-sonarqube
    networks:
      - cp-net
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://cp-sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube-db

networks:
  cp-net:
    driver: bridge

volumes:
  cp_pg:
  sonar_db:
  sonarqube_data:
  sonarqube_extensions:
