services: #apps we want to run in this docker container
  db: #PostgreSQl
    image: postgres:16 #official PostgreSQL 16 image for Docker Hub
    networks:
      - cp-net
    container_name: cp-db #name of the container
    environment:
      POSTGRES_DB: careerpath #database name
      POSTGRES_USER: cp_user #DB username
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "5432:5432" #makes DB available at localhost:5432
    volumes:
      - cp_pg:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - cp-net
    container_name: cp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" #Accessible at http://localhost:5050
    restart: unless-stopped

  backend:
    build:
      context: ../backend
    networks:
      - cp-net
    container_name: cp-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    networks:
      - cp-net
    container_name: cp-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

networks:
  cp-net:
    driver: bridge

volumes:
  cp_pg: