--
-- PostgreSQL database dump
--

\restrict lq8qB0eE82DsOSZqgJ6I2ShvbSvLO5I6ZdihEM6ARaUDvwevxYH9YBCo5mhH60a

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application_status_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_status_history (
    id bigint NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    new_status character varying(255) NOT NULL,
    old_status character varying(255),
    application_id uuid NOT NULL,
    changed_by uuid,
    CONSTRAINT application_status_history_new_status_check CHECK (((new_status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'UNDER_REVIEW'::character varying, 'REJECTED'::character varying, 'ACCEPTED'::character varying])::text[]))),
    CONSTRAINT application_status_history_old_status_check CHECK (((old_status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'UNDER_REVIEW'::character varying, 'REJECTED'::character varying, 'ACCEPTED'::character varying])::text[])))
);


--
-- Name: application_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applications (
    id uuid NOT NULL,
    cover_letter text,
    created_at timestamp(6) with time zone,
    cv_url character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    job_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT applications_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'UNDER_REVIEW'::character varying, 'REJECTED'::character varying, 'ACCEPTED'::character varying])::text[])))
);


--
-- Name: bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks (
    created_at timestamp(6) with time zone NOT NULL,
    job_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: education; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.education (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    degree character varying(255),
    description text,
    end_date date,
    field_of_study character varying(255),
    grade character varying(255),
    institution character varying(255),
    start_date date,
    updated_at timestamp(6) with time zone,
    user_id uuid NOT NULL
);


--
-- Name: experience; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experience (
    id uuid NOT NULL,
    company character varying(255),
    created_at timestamp(6) with time zone,
    description text,
    employment_type character varying(255) NOT NULL,
    end_date date,
    is_current boolean NOT NULL,
    location character varying(255),
    start_date date,
    title character varying(255),
    updated_at timestamp(6) with time zone,
    user_id uuid NOT NULL,
    CONSTRAINT experience_employment_type_check CHECK (((employment_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERNSHIP'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'VOLUNTEER'::character varying])::text[])))
);


--
-- Name: experience_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experience_skills (
    experience_id uuid NOT NULL,
    skill_id integer NOT NULL
);


--
-- Name: job_listings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_listings (
    id uuid NOT NULL,
    company character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    description text,
    expires_at date,
    location character varying(255),
    stack_summary character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    recruiter_id uuid NOT NULL,
    CONSTRAINT job_listings_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING'::character varying, 'PUBLISHED'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT job_listings_type_check CHECK (((type)::text = ANY ((ARRAY['INTERNSHIP'::character varying, 'FULL_TIME'::character varying, 'PART_TIME'::character varying, 'CONTRACT'::character varying])::text[])))
);


--
-- Name: job_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_skills (
    job_id uuid NOT NULL,
    skill_id integer NOT NULL
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    user_id uuid NOT NULL,
    about text,
    ai_opt_in boolean NOT NULL,
    created_at timestamp(6) with time zone,
    cv_url character varying(255),
    first_name character varying(255),
    headline character varying(255),
    last_name character varying(255),
    location character varying(255),
    updated_at timestamp(6) with time zone
);


--
-- Name: recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendations (
    id bigint NOT NULL,
    generated_at timestamp(6) with time zone NOT NULL,
    model_version character varying(255),
    score numeric(6,3) NOT NULL,
    job_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_skills (
    level character varying(255) NOT NULL,
    skill_id integer NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT user_skills_level_check CHECK (((level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    email_verified_at timestamp(6) with time zone,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['SEEKER'::character varying, 'RECRUITER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: application_status_history application_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT application_status_history_pkey PRIMARY KEY (id);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: bookmarks bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (job_id, user_id);


--
-- Name: education education_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education
    ADD CONSTRAINT education_pkey PRIMARY KEY (id);


--
-- Name: experience experience_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience
    ADD CONSTRAINT experience_pkey PRIMARY KEY (id);


--
-- Name: experience_skills experience_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience_skills
    ADD CONSTRAINT experience_skills_pkey PRIMARY KEY (experience_id, skill_id);


--
-- Name: job_listings job_listings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_listings
    ADD CONSTRAINT job_listings_pkey PRIMARY KEY (id);


--
-- Name: job_skills job_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_skills
    ADD CONSTRAINT job_skills_pkey PRIMARY KEY (job_id, skill_id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (user_id);


--
-- Name: recommendations recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: skills uk85woe63nu9klkk9fa73vf0jd0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT uk85woe63nu9klkk9fa73vf0jd0 UNIQUE (name);


--
-- Name: applications uki3q7htrq10m6sedv6qhimbafh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT uki3q7htrq10m6sedv6qhimbafh UNIQUE (job_id, user_id);


--
-- Name: user_skills user_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_pkey PRIMARY KEY (skill_id, user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: recommendations fk2i3ieoxkkvo231xe6qyl4u0wa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT fk2i3ieoxkkvo231xe6qyl4u0wa FOREIGN KEY (job_id) REFERENCES public.job_listings(id);


--
-- Name: recommendations fk3c9w1lipqdutm65a9inevwfp0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT fk3c9w1lipqdutm65a9inevwfp0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: profiles fk410q61iev7klncmpqfuo85ivh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: job_listings fkaxw6cf6p1s8q8o0krh9semjqw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_listings
    ADD CONSTRAINT fkaxw6cf6p1s8q8o0krh9semjqw FOREIGN KEY (recruiter_id) REFERENCES public.users(id);


--
-- Name: education fkc8qg4a1sd3texfadb2d7eyhgx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education
    ADD CONSTRAINT fkc8qg4a1sd3texfadb2d7eyhgx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookmarks fkdbsho2e05w5r13fkjqfjmge5f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkdbsho2e05w5r13fkjqfjmge5f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookmarks fkdjllgsi5ra84lu26m6fnq83nm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkdjllgsi5ra84lu26m6fnq83nm FOREIGN KEY (job_id) REFERENCES public.job_listings(id);


--
-- Name: job_skills fke10ho7um0atjm67b9dgokmfyx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_skills
    ADD CONSTRAINT fke10ho7um0atjm67b9dgokmfyx FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: application_status_history fkesbs9nouqpdmb32csba9ugrx4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT fkesbs9nouqpdmb32csba9ugrx4 FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: job_skills fkf628u8q1dd9nsdb1ga253i018; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_skills
    ADD CONSTRAINT fkf628u8q1dd9nsdb1ga253i018 FOREIGN KEY (job_id) REFERENCES public.job_listings(id);


--
-- Name: application_status_history fkfdvnrm195jdlti0syxo6qah6h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT fkfdvnrm195jdlti0syxo6qah6h FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: applications fkfsfqljedcla632u568jl5qf3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkfsfqljedcla632u568jl5qf3w FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_skills fkh223y61gwijpgqt6nlsuti07g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT fkh223y61gwijpgqt6nlsuti07g FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: experience_skills fko88ck6rbx84b1jntrarjgnfuc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience_skills
    ADD CONSTRAINT fko88ck6rbx84b1jntrarjgnfuc FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: experience fko8gihpwob4qiyigh869833ove; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience
    ADD CONSTRAINT fko8gihpwob4qiyigh869833ove FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: applications fkpbyv55kmktbq4dm3lx77d59dd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkpbyv55kmktbq4dm3lx77d59dd FOREIGN KEY (job_id) REFERENCES public.job_listings(id);


--
-- Name: experience_skills fkqu01wblas164c21wdm3jfa5ku; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experience_skills
    ADD CONSTRAINT fkqu01wblas164c21wdm3jfa5ku FOREIGN KEY (experience_id) REFERENCES public.experience(id);


--
-- Name: user_skills fkro13if9r7fwkr5115715127ai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT fkro13if9r7fwkr5115715127ai FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict lq8qB0eE82DsOSZqgJ6I2ShvbSvLO5I6ZdihEM6ARaUDvwevxYH9YBCo5mhH60a

