-- Generated from existing JPA entities

    create table application_status_history (
        changed_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        application_id uuid not null,
        changed_by uuid,
        new_status varchar(255) not null check (new_status in ('SUBMITTED','UNDER_REVIEW','REJECTED','ACCEPTED')),
        old_status varchar(255) check (old_status in ('SUBMITTED','UNDER_REVIEW','REJECTED','ACCEPTED')),
        primary key (id)
    );

    create table applications (
        created_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        id uuid not null,
        job_id uuid not null,
        user_id uuid not null,
        cover_letter text,
        cv_url varchar(255),
        status varchar(255) not null check (status in ('SUBMITTED','UNDER_REVIEW','REJECTED','ACCEPTED')),
        primary key (id),
        unique (job_id, user_id)
    );

    create table bookmarks (
        created_at timestamp(6) with time zone not null,
        job_id uuid not null,
        user_id uuid not null,
        primary key (job_id, user_id)
    );

    create table education (
        end_date date,
        start_date date,
        created_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        id uuid not null,
        user_id uuid not null,
        degree varchar(255),
        description text,
        field_of_study varchar(255),
        grade varchar(255),
        institution varchar(255),
        primary key (id)
    );

    create table experience (
        end_date date,
        is_current boolean not null,
        start_date date,
        created_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        id uuid not null,
        user_id uuid not null,
        company varchar(255),
        description text,
        employment_type varchar(255) not null check (employment_type in ('FULL_TIME','PART_TIME','INTERNSHIP','CONTRACT','FREELANCE','VOLUNTEER')),
        location varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table experience_skills (
        skill_id integer not null,
        experience_id uuid not null,
        primary key (skill_id, experience_id)
    );

    create table job_listings (
        expires_at date,
        created_at timestamp(6) with time zone,
        deleted_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        id uuid not null,
        recruiter_id uuid not null,
        company varchar(255) not null,
        description text,
        location varchar(255),
        stack_summary varchar(255),
        status varchar(255) not null check (status in ('DRAFT','PENDING','PUBLISHED','CLOSED')),
        title varchar(255) not null,
        type varchar(255) not null check (type in ('INTERNSHIP','FULL_TIME','PART_TIME','CONTRACT')),
        primary key (id)
    );

    create table job_skills (
        skill_id integer not null,
        job_id uuid not null,
        primary key (skill_id, job_id)
    );

    create table profiles (
        ai_opt_in boolean not null,
        created_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        user_id uuid not null,
        about text,
        cv_url varchar(255),
        first_name varchar(255),
        headline varchar(255),
        last_name varchar(255),
        location varchar(255),
        primary key (user_id)
    );

    create table recommendations (
        score numeric(6,3) not null,
        generated_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        job_id uuid not null,
        user_id uuid not null,
        model_version varchar(255),
        primary key (id)
    );

    create table skills (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table user_skills (
        skill_id integer not null,
        user_id uuid not null,
        level varchar(255) not null check (level in ('BEGINNER','INTERMEDIATE','ADVANCED')),
        primary key (skill_id, user_id)
    );

    create table users (
        created_at timestamp(6) with time zone,
        email_verified_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        id uuid not null,
        email varchar(255) not null unique,
        password_hash varchar(255) not null,
        role varchar(255) not null check (role in ('SEEKER','RECRUITER','ADMIN')),
        primary key (id)
    );

    alter table if exists application_status_history 
       add constraint FKfdvnrm195jdlti0syxo6qah6h 
       foreign key (application_id) 
       references applications;

    alter table if exists application_status_history 
       add constraint FKesbs9nouqpdmb32csba9ugrx4 
       foreign key (changed_by) 
       references users;

    alter table if exists applications 
       add constraint FKpbyv55kmktbq4dm3lx77d59dd 
       foreign key (job_id) 
       references job_listings;

    alter table if exists applications 
       add constraint FKfsfqljedcla632u568jl5qf3w 
       foreign key (user_id) 
       references users;

    alter table if exists bookmarks 
       add constraint FKdjllgsi5ra84lu26m6fnq83nm 
       foreign key (job_id) 
       references job_listings;

    alter table if exists bookmarks 
       add constraint FKdbsho2e05w5r13fkjqfjmge5f 
       foreign key (user_id) 
       references users;

    alter table if exists education 
       add constraint FKc8qg4a1sd3texfadb2d7eyhgx 
       foreign key (user_id) 
       references users;

    alter table if exists experience 
       add constraint FKo8gihpwob4qiyigh869833ove 
       foreign key (user_id) 
       references users;

    alter table if exists experience_skills 
       add constraint FKqu01wblas164c21wdm3jfa5ku 
       foreign key (experience_id) 
       references experience;

    alter table if exists experience_skills 
       add constraint FKo88ck6rbx84b1jntrarjgnfuc 
       foreign key (skill_id) 
       references skills;

    alter table if exists job_listings 
       add constraint FKaxw6cf6p1s8q8o0krh9semjqw 
       foreign key (recruiter_id) 
       references users;

    alter table if exists job_skills 
       add constraint FKf628u8q1dd9nsdb1ga253i018 
       foreign key (job_id) 
       references job_listings;

    alter table if exists job_skills 
       add constraint FKe10ho7um0atjm67b9dgokmfyx 
       foreign key (skill_id) 
       references skills;

    alter table if exists profiles 
       add constraint FK410q61iev7klncmpqfuo85ivh 
       foreign key (user_id) 
       references users;

    alter table if exists recommendations 
       add constraint FK2i3ieoxkkvo231xe6qyl4u0wa 
       foreign key (job_id) 
       references job_listings;

    alter table if exists recommendations 
       add constraint FK3c9w1lipqdutm65a9inevwfp0 
       foreign key (user_id) 
       references users;

    alter table if exists user_skills 
       add constraint FKh223y61gwijpgqt6nlsuti07g 
       foreign key (skill_id) 
       references skills;

    alter table if exists user_skills 
       add constraint FKro13if9r7fwkr5115715127ai 
       foreign key (user_id) 
       references users;
