version: "3.8"

services:
  # --- SONARQUBE DATABASE ---
  sonarqube-db:
    image: postgres:16
    container_name: cp-sonar-db
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonar_db:/var/lib/postgresql/data
    networks:
      - cp-net
    restart: unless-stopped

  # --- SONARQUBE ---
  sonarqube:
    image: sonarqube:10.4.1-community
    container_name: cp-sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://cp-sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube-db
    networks:
      - cp-net
    restart: unless-stopped

networks:
  cp-net:
    external: true

volumes:
  sonar_db:
  sonarqube_data:
  sonarqube_extensions:
