default:
  tags:
    - docker
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - backend/.gradle/wrapper
      - backend/.gradle/caches
      - backend/.gradle/buildOutputCleanup

stages:
  - build
  - integration
  - analyze

# ---------------- BACKEND BUILD (CI RUNTIME IMAGE) ----------------
backend-ci-build:
  stage: build
  image: gradle:8.5-jdk17
  before_script:
    - cd backend
  script:
    - ./gradlew assemble --no-daemon
  artifacts:
    expire_in: 1 week
    paths:
      - backend/build/libs/
  only:
    - dev


# ---------------- FRONTEND BUILD ----------------
frontend-build:
  stage: build
  image: node:20
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - frontend/node_modules
  before_script:
    - cd frontend
  script:
    - npm ci --prefer-offline --no-audit --legacy-peer-deps
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  only:
    - dev


# ---------------- GOOGLE LIGHTHOUSE ----------------
frontend-lighthouse:
  stage: analyze
  image: node:20
  dependencies:
    - frontend-build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci --prefer-offline --no-audit --legacy-peer-deps
  script:
    - npm run lighthouse
  artifacts:
    when: always
    paths:
      - frontend/lhci-reports/
    expire_in: 1 week
  allow_failure: true

# ---------------- INTEGRATION TESTS ----------------
integration-test:
  stage: integration
  image: gradle:8.5-jdk17
  variables:
    TC_CLOUD_TOKEN: "$TC_CLOUD_TOKEN"
  dependencies:
    - backend-ci-build
  before_script:
    - curl -fsSL https://app.testcontainers.cloud/bash | bash
    - cd backend
  script:
    - ./gradlew integrationTest --no-daemon -stacktrace -Dspring.profiles.active=test -Dtestcontainers.cloud.enabled=true "-Dtestcontainers.cloud.token=$TC_CLOUD_TOKEN"
  allow_failure: false
  only:
    - dev
