default:
  tags:
    - docker

stages:
  - build
  - integration
  - analyze

# ---------------- BACKEND BUILD (CI RUNTIME IMAGE) ----------------
backend-ci-build:
  stage: build
  image: gradle:8.5-jdk17
  before_script:
    - cd backend
  script:
    - ./gradlew assemble --no-daemon
  artifacts:
    expire_in: 1 week
    paths:
      - backend/build/libs/
  only:
    - dev
    - dev-test


# ---------------- FRONTEND BUILD ----------------
frontend-build:
  stage: build
  image: node:20
  before_script:
    - cd frontend
  script:
    - npm ci --prefer-offline --no-audit --legacy-peer-deps
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  only:
    - dev
    - dev-test



# ---------------- INTEGRATION TESTS ----------------
integration-test:
  stage: integration
  image: gradle:8.5-jdk17
  variables:
    TC_CLOUD_TOKEN: "$TC_CLOUD_TOKEN"
  dependencies:
    - backend-ci-build
    - frontend-build
  before_script:
    - curl -fsSL https://app.testcontainers.cloud/bash | bash
    - cd backend
  script:
    - ./gradlew integrationTest --no-daemon -stacktrace -Dspring.profiles.active=test -Dtestcontainers.cloud.enabled=true "-Dtestcontainers.cloud.token=$TC_CLOUD_TOKEN"
  allow_failure: false
  only:
    - dev
    - dev-test


# ---------------- SONARQUBE (OPTIONAL) ----------------
backend-sonarqube:
  stage: analyze
  image: gradle:8.5-jdk17
  dependencies:
    - frontend-build
    - backend-ci-build
  script:
    - cd backend
    - ./gradlew sonarqube \
      -Dsonar.projectKey=careerpath-backend \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.token=$SONAR_TOKEN_BACKEND \
      -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
  allow_failure: true
  only:
    - dev
    - dev-test
