default:
  tags:
    - docker

stages:
  - build
  - integration
  - analyze

# ---------------- BACKEND BUILD ----------------
backend-docker-build:
  stage: build
  image: docker:27.0.3
  services:
    - name: docker:dind
      command: ["--tls=false"]
  script:
    - docker build -f backend/Dockerfile.ci -t cp-backend-ci .
  artifacts:
    expire_in: 1 week
    paths: []
#  only:
#    - dev

# ---------------- FRONTEND BUILD ----------------
frontend-build:
  stage: build
  image: node:20
  before_script:
    - cd frontend
  script:
    - npm ci --prefer-offline --no-audit --legacy-peer-deps
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
#  only:
#    - dev

# ---------------- INTEGRATION TESTS ----------------
integration-test:
  stage: integration
  image: docker:27.0.3
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  dependencies:
    - backend-docker-build
    - frontend-build
  script:
    - export TC_CLOUD_TOKEN="$TC_CLOUD_TOKEN"
    - docker compose -f docker/compose/docker-compose.ci.yml up --build --abort-on-container-exit
  after_script:
    - docker compose -f docker/compose/docker-compose.ci.yml down
  allow_failure: false
#  only:
#    - dev

# ---------------- SONARQUBE (OPTIONAL) ----------------
backend-sonarqube:
  stage: analyze
  image: gradle:8.5-jdk17
  dependencies:
    - frontend-build
  script:
    - cd backend
    - ./gradlew sonarqube \
      -Dsonar.projectKey=careerpath-backend \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.token=$SONAR_TOKEN_BACKEND \
      -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
  allow_failure: true
#  only:
#    - dev
