default:
  tags:
    - docker

stages:
  - lint
  - build
  - test
  - analyze

# ---------- LINT ----------
frontend-lint:
  stage: lint
  image: node:20
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/frontend/.npm"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/.npm/
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci --prefer-offline --cache .npm --no-audit --legacy-peer-deps
  script:
    - npx eslint . --format json --output-file eslint-report.json
  artifacts:
    paths:
      - frontend/eslint-report.json
    when: always
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - frontend/**/*
  #    - when: never
  allow_failure: false

backend-lint:
  stage: lint
  image:
    name: gradle:8.4.0-jdk17
    pull_policy: if-not-present
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    key: gradle-cache-${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/wrapper/
      - .gradle/caches/
      - backend/.gradle/
  before_script:
    - cd backend
  script:
    - ./gradlew clean checkstyleMain checkstyleTest --no-daemon --console=plain
  artifacts:
    when: always
    paths:
      - backend/build/reports/
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - backend/**/*
  #    - when: never
  allow_failure: false

# ---------- BUILD ----------
frontend-build:
  stage: build
  image: node:20
  dependencies:
    - frontend-lint
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/frontend/.npm"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/.npm/
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci --prefer-offline --cache .npm --no-audit --legacy-peer-deps
  script:
    - npm run build -- --configuration=production
  artifacts:
    name: "frontend-dist-$CI_COMMIT_SHORT_SHA"
    paths:
      - frontend/dist/
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - frontend/**/*
  #    - when: never
  allow_failure: false

backend-build:
  stage: build
  image:
    name: gradle:8.4.0-jdk17
    pull_policy: if-not-present
  dependencies:
    - backend-lint
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    key: gradle-cache-${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/wrapper/
      - .gradle/caches/
      - backend/.gradle/
  before_script:
    - cd backend
  script:
    - ./gradlew assemble --no-daemon --build-cache
  artifacts:
    name: "backend-jar-$CI_COMMIT_SHORT_SHA"
    paths:
      - backend/build/libs/
      - backend/build/classes/
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - backend/**/*
  #    - when: never
  allow_failure: false

# ---------- TEST ----------
frontend-test:
  stage: test
  image: node:20
  dependencies:
    - frontend-build
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/frontend/.npm"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/.npm/
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci --prefer-offline --cache .npm --no-audit --legacy-peer-deps
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - frontend/coverage/
    reports:
      junit: frontend/test-results.xml
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - frontend/**/*
  #    - when: never
  allow_failure: false

backend-test:
  stage: test
  image: gradle:8.4.0-jdk17
  dependencies:
    - backend-build
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g'"
  cache:
    key: gradle-cache-${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/wrapper/
      - .gradle/caches/
      - backend/.gradle/
  before_script:
    - cd backend
  script:
    - ./gradlew test jacocoTestReport --no-daemon --build-cache
  artifacts:
    when: always
    paths:
      - backend/build/test-results/
      - backend/build/reports/tests/
      - backend/build/reports/jacoco/test/jacocoTestReport.xml
    reports:
      junit: backend/build/test-results/test/*.xml
    expire_in: 1 week
  #  rules:
  #    - changes:
  #        - backend/**/*
  #    - when: never
  allow_failure: false
  tags:
    - docker

# ---------- ANALYZE ----------
backend-sonarqube:
  stage: analyze
  image:
    name: gradle:8.5-jdk17
    pull_policy: if-not-present
  dependencies:
    - backend-test
    - backend-build
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: gradle-sonar-cache
    paths:
      - .gradle/wrapper/
      - .gradle/caches/
      - backend/.gradle/
      - .sonar/cache
  before_script:
    - cd backend
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=careerpath-backend -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN_BACKEND -Dsonar.java.binaries=build/classes/java/main -Dsonar.junit.reportPaths=build/test-results/test -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
  artifacts:
    when: always
    paths:
      - backend/build/reports/
    expire_in: 1 week
  allow_failure: false

frontend-sonarqube:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    pull_policy: if-not-present
  dependencies:
    - frontend-test
  variables:
    SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: sonar-frontend-cache
    paths:
      - .sonar/cache
  before_script:
    - cd frontend
  script:
    - sonar-scanner -Dsonar.typescript.tsconfigPath=tsconfig.sonar.json -Dsonar.projectKey=careerpath-frontend -Dsonar.sources=src -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN_FRONTEND -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.junit.reportPaths=test-results.xml
  artifacts:
    when: always
    paths:
      - frontend/coverage/
      - frontend/test-results.xml
    expire_in: 1 week
  allow_failure: false
